name: Daily QA Job Bot

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Packages
        run: pip list

      - name: Run Job Bot
        run: |
          echo "Running job_bot.py"
          python job_bot.py

      - name: Show Files
        run: |
          pwd
          ls -la
          find . -name "*.xlsx"

      - name: Upload Excel
        uses: actions/upload-artifact@v4
        with:
          name: qa-job-report
          path: QA_Jobs_*.xlsx

      - name: Send Email
        if: always()
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python send_email.py
